#ifndef INC_0X0F_FUNCTION_POINTERS_FUNCTION_POINTERS_H
#define INC_0X0F_FUNCTION_POINTERS_FUNCTION_POINTERS_H

void print_name(char *name, void (*f)(char *));

#endif /* INC_0X0F_FUNCTION_POINTERS_FUNCTION_POINTERS_H */
